version: '1.0'

services:
  postgres:
    image: postgres:13
    container_name: postgres-service
    environment:
      POSTGRES_DB: consumption-service-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: consumer-service-app
    container_name: consumer-service-app-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/consumption-service-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  postgres_data: